### ISSUE TITLE
Error when tapped "Open Scanner" @neon67

### ISSUE THREAD

**Issue by nigga1604** [neon97/QR-CODE-Scanner-Generator#1]
I am getting this error when i tap on the button.@neon97 can you help me??

E/flutter (32108): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method request_permission on channel de.mintware.barcode_scan)
E/flutter (32108): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (32108): <asynchronous suspension>
E/flutter (32108): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (32108): #2      BarcodeScanner.scan (package:barcode_scan/barcode_scan.dart:32:24)
E/flutter (32108): #3      _ScanPageState.build.<anonymous closure> (package:qrfin/scan.dart:46:59)
E/flutter (32108): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (32108): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (32108): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (32108): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (32108): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (32108): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (32108): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (32108): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (32108): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (32108): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (32108): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (32108): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (32108): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (32108): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (32108): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (32108): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (32108): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (32108): #21     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (32108): #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (32108): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (32108): #24     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (32108): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**Comment by neon97** [comment]
"No implementation found for method request_permission on channel de.mintware.barcode_scan"
This is the error would suggest you to have a flutter clean for the project then try running the project
As sometimes on the debug mode when we add the plugin we almost get the permmision problems, so,
As to know the device that what permission you need just restart the application with   "flutter clean"..
Hope this could solve your issue...
