### ISSUE TITLE
I added some features

### ISSUE THREAD

**Issue by sinanurun** [neon97/QR-CODE-Scanner-Generator#4]
hi 
thanks a lot for this app, 
I added some features like student list and exam list
With the addition I made, a student list and exam list can be created. With the additions I made, whether the students participating in an exam are on the exam list is checked by QR codes and recorded in the exam session list.
Thank you again for your contributions
[https://github.com/sinanurun/QR-Code-Student-Exam-List](https://github.com/sinanurun/QR-Code-Student-Exam-List)

@neon97  @sinanurun

**Comment by neon97** [comment]
That really a good one KUDOS !! to your work @sinanurun ..
And yup !! thanks for being here..
Would always share the best of best plugins that #flutter developers can easily use.
Get with me on my ..places 😃 
https://github.com/neon97
